export const features = {
  aiObituaryEnabled: true,
  aiBiographyEnabled: true,
  chatEnabled: true,
  eventsEnabled: true,
  donationsEnabled: true,
  ribbonEconomyEnabled: true,
  marketplaceEnabled: true,
  nftEnabled: true,
  directoryEnabled: true,
  liveRoomsEnabled: true,
  advancedAIEnabled: true,
  arVrEnabled: true,
  memoryVaultEnabled: true,
  timeCapsuleEnabled: true,
  legacyLettersEnabled: true,
  familyTreeEnabled: true,
  virtualSpacesEnabled: true,
  qrCodesEnabled: true,
  scrapbookEnabled: true,
  memoryStreaksEnabled: true,
  seasonalDecorationsEnabled: true,
  guestBrowsingEnabled: true,
  onboardingEnabled: true,
  candleAnimationEnabled: true,
  celebrityContentEnabled: true,
  newsEnabled: true,
  socialSharingEnabled: true,
  legacyLinksEnabled: true,
  livingTributesEnabled: true,
  appreciationLettersEnabled: true,
  dailyPromptsEnabled: true,
  smartRemindersEnabled: true,
  engagementStreaksEnabled: true,
  inviteLinksEnabled: true,
  campaignsEnabled: true,
  shareCardTemplatesEnabled: true,
  giftEconomyEnabled: true,
  legacyPointsEnabled: true,
  trustSystemEnabled: true,
  contentImportEnabled: true,
  fundraisingV2Enabled: true,
  duplicateDetectionEnabled: true,
  directoryImportEnabled: true,
  lifecycleStagesEnabled: true,
  celebrityRequestsEnabled: true,
  premiumSubscriptionsEnabled: true,
  paywallEnabled: true,
  lifeTimelineEnabled: true,
  milestonesEnabled: true,
  photoTaggingEnabled: true,
  faceRecognitionEnabled: false, // Requires ML service API keys
  autoRemindersEnabled: true,
  directoryMassImportEnabled: true,
  fullTextSearchEnabled: true,
  imageUploadEnabled: true,
  analyticsEnabled: true,
  deepLinksEnabled: true,
  i18nEnabled: true,
  offlineCacheEnabled: true,
  accessibilityHelpersEnabled: true,
  realtimeCollaborationEnabled: true,
  adminDashboardEnabled: true,
  emailDeliveryEnabled: true,
  aiLifeStoryEnabled: true,
  liveBroadcastEnabled: true,
  proximityFeedEnabled: true,
  weddingPagesEnabled: true,
  petPagesEnabled: true,
  welcomeJourneyEnabled: true,
  questsEnabled: true,
  surpriseDelightEnabled: true,
  personalizedFeedEnabled: true,
  mysteryGiftDropsEnabled: true,
  creatorEconomyEnabled: true,
  serviceMarketplaceEnabled: true,
  honorFundraiserEnabled: true,

  // Page Stewardship & Transfer System
  pageStewardshipEnabled: true,
  pageTransfersEnabled: true,
  pageValuationEnabled: true,
  stewardshipMarketplaceEnabled: false, // Phase 3 — not yet implemented
  communityGovernanceEnabled: false, // Phase 3 — not yet implemented

  // Progressive Feature Unlocking
  progressiveUnlockingEnabled: true,
  creatorLevelGateEnabled: true,

  // Baby Journey ("Little Arcs")
  babyJourneyEnabled: true,
  babyGrowthTrackingEnabled: true,

  // Relationship Lifecycle
  relationshipLifecycleEnabled: true,
} as const;
